name: Update Meilisearch index with BGG data

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:
  push: 
    branches:
      - 'master'
jobs:
  index:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - run: python -m pip install --upgrade pip
    - run: pip install -r scripts/requirements.txt
    - name: Run script if secret is set
      env:
        APIKEY: ${{secrets.APIKEY}}
        PASSWORD: ${{secrets.PASSWORD}}
      if: env.APIKEY != null && env.PASSWORD != null
      run: |
        python scripts/download_and_index.py --apikey ${{env.APIKEY}} --password ${{env.PASSWORD}}
